#!/usr/bin/env bash

fetch_wifi_device_name() {
  networksetup -listallhardwareports | grep -A 1 Wi-Fi | head -n2 | tail -n1 | awk '{print $2}'
}

wifi_is_on() {
  networksetup -getairportpower $device_name | grep -q On
}

switch_wifi() {
  local device_name=$1
  local device_action=$2
  echo "Switching Wi-Fi $device_action..."
  networksetup -setairportpower $device_name $device_action
}

main() {
  local device_name=$(fetch_wifi_device_name)

  if ( wifi_is_on ); then
    switch_wifi $device_name Off
  else
    switch_wifi $device_name On
  fi
}
main
